{% set name = "csdms-permamodel-frostnumber" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel

requirements:
  build:
    - bmi-babel
    - permamodel
  run:
    - bmi-babel
    - permamodel

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: https://github.com/permamodel/permamodel
  license: MIT
  summary: The Frost-number model from Permamodel.
  dev_url: https://github.com/permamodel/permamodel
