{% set name = "csdms-permamodel-frostnumber" %}
{% set version = "0.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - babelizer
    - permamodel
  run:
    - cca-tools
    - permamodel

test:
  requires:
    - netcdf-fortran=4.4.4=5  # tmp fix for ESMF
    - pymt

about:
  home: http://csdms.colorado.edu/wiki/Model:Frost_Model
  license: MIT
  summary: The point version of the Frost Number model from Permamodel.
  dev_url: https://github.com/permamodel/permamodel
