{% set name = "csdms-permamodel" %}
{% set version = "0.1" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/permamodel/permamodel

requirements:
  build:
    - bmi-babel
    - permamodel
  run:
    - bmi-babel
    - permamodel

test:
  requires:
    - pymt
    - bmi-tester
