{% set name = "csdms-permamodel-frostnumber" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1

requirements:
  build:
    - babelizer
    - permamodel
  run:
    - babelizer
    - permamodel

test:
  requires:
    - pymt

about:
  home: http://csdms.colorado.edu/wiki/Model:Frost_Model
  license: MIT
  summary: The point version of the Frost Number model from Permamodel.
  dev_url: https://github.com/permamodel/permamodel
